

services:


      db:
        image: postgres:15
        container_name: ${DB_NAME}
        ports:
          - "${DB_PORT}:5432"
        environment:
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_USER: ${DB_USERNAME}
          POSTGRES_DB: ${DB_NAME}
        volumes:
          - postgres15_volumes:/var/lib/postgresql/data


volumes:
  postgres15_volumes:
    external: true
