name: Docker Image CI

on:
  push:
    branches: [ "staging" ]
  pull_request:

    branches: [ "staging" ]
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Processing step
        run: echo "processing"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 20

      - name: Install dependencies
        run: npm install

      - name: run test
        run: npm run test

    

